# -*- coding: utf-8 -*-
"""TAI-IP_Task2_Sports_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7xM3V2ePGjks4dSBrtI1tIh-9UsN-EG
"""

import os
from google.colab import files
uploaded = files.upload()
print(os.getcwd())

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import datetime as dt
from scipy import stats


dataframe= pd.read_csv("fifa_eda_stats.csv")
dataframe

"""#Data Cleaning

Removing the Duplicate values
"""

dataframe.drop_duplicates()
dataframe.sample(10)

dataframe.info()

"""# Droping unnessesory columns"""

dataframe.drop(columns=['International Reputation','Jersey Number','Loaned From','Weight'],axis=1,inplace=True)
dataframe.isna().sum()

dataframe.fillna(dataframe.median(),inplace=True)
dataframe.info()

"""# What is the distribution of the players AGE ?"""

sns.kdeplot(dataframe['Age'], fill=True, color='g')

"""# How many players in each position?"""

c = pd.DataFrame(dataframe.groupby("Position")['Position'].count().sort_values(ascending=False).head(20))
sns.barplot(data = c, x=c.index , y='Position',color = 'Green')
plt.xticks(rotation = 45);

"""# what is the range of overall evaluation for the football players ?"""

sns.histplot(dataframe['Overall'],color = 'b')

"""# What is the relation between the Value the fifa put for the player and wage the players take in fact"""

sns.jointplot(data=dataframe,x='Value',y='Wage')

"""# Number of players evaluated by there work rate ?"""

sns.countplot(data=dataframe,y='Work Rate')
plt.xticks(rotation=45)

"""# Finding the maximum stamina from each player"""

max_stamina = dataframe.groupby('Name')[['Stamina']].max().sort_values(by='Stamina',ascending = False).head(31)
plt.figure(figsize=[15,8])
sns.barplot(x=max_stamina['Stamina'],y=max_stamina.index)
plt.title(' Total shots from each player top 30')
plt.xticks(rotation=45)

"""# What is the most preffered foot for the players"""

x=dataframe['Preferred Foot'].value_counts()
y=['Right foot','Left foot']
cols = ['c','m']
plt.pie(x,labels=y,colors=cols)

